language: node_js
install: npm install
script: npm run build  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 9166f288b3469c266d218cb24117a035492db27d  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./docs