language: node_js
node_js: 10
install: npm install
script: npm run build
before_deploy:
  - npm run copy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 9166f288b3469c266d218cb24117a035492db27d  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./docs